Video 4893 show network for main participant
twilio/twilio-video-app-react pull request #499
Opened 2021-04-20 23:42 UTC by olipyskoty

**Contributing to Twilio**

> All third party contributors acknowledge that any contributions they provide will be made under the same open source license that the open source project is provided under.

- [x] I acknowledge that all my contributions will be made under the project's license.

## Pull Request Details

### JIRA link(s):

- [VIDEO-4893](https://issues.corp.twilio.com/browse/VIDEO-4893)

### Description

This PR adds the network quality indicator to the main participant. This is the same network quality indicator that is used by the `<ParticipantInfo />` component. We decided to move the styling to the `<NetworkQualityLevel />` in order to remove the empty boxes from the participant thumbnails in P2P rooms. 

Screenshots:
**Main participant === localParticipant:**
![Screen Shot 2021-04-20 at 7 07 48 PM](https://user-images.githubusercontent.com/77076398/115476562-1b87e780-a210-11eb-8426-88f58fe94774.png)

**Main participant !== localParticipant:**
![Screen Shot 2021-04-20 at 7 07 14 PM](https://user-images.githubusercontent.com/77076398/115476592-2d698a80-a210-11eb-81c7-c8b1f874561c.png)

## Burndown

### Before review
* [ ] Updated CHANGELOG.md if necessary
* [ ] Added unit tests if necessary
* [ ] Updated affected documentation
* [x] Verified locally with `npm test`
* [x] Manually sanity tested running locally
* [x] Included screenshot as PR comment (if needed)
* [x] Ready for review

### Before merge
* [ ] Got one or more +1s
* [ ] Re-tested if necessary

2021-04-20 23:42 UTC, olipyskoty commented
@timmydoza I didn't think any unit tests needed to be updated for the `<MainParticipantInfo />` as there doesn't appear to be anything related to the network quality in the `<ParticipantInfo />` unit tests, but please let me know if I should add some.

2021-04-22 18:27 UTC, timmydoza requested changes
Looks good! I think that's it. Just one tiny change request.

2021-04-22 18:27 UTC, timmydoza commented on src/components/MainParticipantInfo/MainParticipantInfo.tsx
> +    marginRight: '0.4em',
I think the network container increased the height of the `identity` div just a little bit, which is totally fine. But it looks like things aren't centered vertically now. Let's add `align-items: 'center',` to the `identity` class.

Before:
![image](https://user-images.githubusercontent.com/12685223/115766961-d1b11580-a365-11eb-8664-7198c019c08c.png)

After: 
![image](https://user-images.githubusercontent.com/12685223/115767007-df669b00-a365-11eb-9e51-682a423f0cbb.png)

2021-04-22 19:47 UTC, timmydoza approved these changes

2021-04-22 20:11 UTC, merged