Merge feature/virtualbackground onto master
twilio/twilio-video-app-react pull request #574
Opened 2021-08-06 19:51 UTC by gabriel-jt

**Contributing to Twilio**

> All third party contributors acknowledge that any contributions they provide will be made under the same open source license that the open source project is provided under.

- [ ] I acknowledge that all my contributions will be made under the project's license.

## Pull Request Details

### JIRA link(s):

- [VIDEO-6414](https://issues.corp.twilio.com/browse/VIDEO-6414)

### Description

Merge the virtual background feature onto master

## Burndown

### Before review
* [ ] Updated CHANGELOG.md if necessary
* [ ] Added unit tests if necessary
* [ ] Updated affected documentation
* [ ] Verified locally with `npm test`
* [ ] Manually sanity tested running locally
* [ ] Included screenshot as PR comment (if needed)
* [ ] Ready for review

### Before merge
* [ ] Got one or more +1s
* [ ] Re-tested if necessary

2021-08-06 20:01 UTC, charliesantos approved these changes
Let's get @timmydoza 's +1 before merging.

2021-08-06 21:29 UTC, timmydoza requested changes
Nearly there! Just some quick changes needed...

2021-08-06 21:29 UTC, timmydoza commented on src/components/MenuBar/MenuBar.tsx
> +              <Grid container justify="flex-end">
This should be `justifyContent="flex-end"`. There's a warning in the console about it (but only when when browser width is reduced to show the mobile styles). 

![image](https://user-images.githubusercontent.com/12685223/128572250-a81d8d36-aaa0-478c-a728-9fc17a615b9c.png)

2021-08-06 21:29 UTC, timmydoza commented on package.json
> +    "@types/react": "17.0.11",
Let's keep React at `^16.9.19`

2021-08-06 21:29 UTC, timmydoza commented on CHANGELOG.md
> +- This release adds a virtual background feature. This feature allows users to blur their background or apply a background image from the background selection window. The virtual backgrounds are appl
Let's add a link to the PR at the end of the description:
```suggestion
- This release adds a virtual background feature. This feature allows users to blur their background or apply a background image from the background selection window. The virtual backgrounds are applied to the video tracks using the [Twilio Video Processors SDK](https://www.twilio.com/docs/video/video-processors). For more information, please view this [blog post](https://www.twilio.com/blog/introducing-virtual-backgrounds-browser-based-video-applications). [#574](https://github.com/twilio/twilio-video-app-react/pull/574)
```

2021-08-06 21:29 UTC, timmydoza commented on CHANGELOG.md
> +
Also here let's add information about the package upgrades that happened in #568.

```
### Dependency Upgrades
-`@material-ui/core` has been updated from 4.9.1. to 4.12.3. [#568](https://github.com/twilio/twilio-video-app-react/pull/568)
-`@material-ui/icons` has been updated from 4.9.1. to 4.11.12. [#568](https://github.com/twilio/twilio-video-app-react/pull/568)
-`@twilio/conversations` has been updated from 1.1.0. to 1.2.3. [#568](https://github.com/twilio/twilio-video-app-react/pull/568)
```

2021-08-06 21:35 UTC, timmydoza commented
Also, when I run `npm install`, there is a change made to `package-lock.json`. Let's commit that change.

2021-08-09 16:02 UTC, charliesantos approved these changes

2021-08-09 16:10 UTC, timmydoza approved these changes

2021-08-09 16:31 UTC, merged