Grid mode pagination
twilio/twilio-video-app-react pull request #654
Opened 2022-03-08 16:55 UTC by timmydoza

**Contributing to Twilio**

> All third party contributors acknowledge that any contributions they provide will be made under the same open source license that the open source project is provided under.

- [ ] I acknowledge that all my contributions will be made under the project's license.

## Pull Request Details

### JIRA link(s):

- [AHOYAPPS-0000](https://issues.corp.twilio.com/browse/AHOYAPPS-0000)

### Description

A description of what this PR does.

## Burndown

### Before review
* [ ] Updated CHANGELOG.md if necessary
* [ ] Added unit tests if necessary
* [ ] Updated affected documentation
* [ ] Verified locally with `npm test`
* [ ] Manually sanity tested running locally
* [ ] Included screenshot as PR comment (if needed)
* [ ] Ready for review

### Before merge
* [ ] Got one or more +1s
* [ ] Re-tested if necessary

2022-03-11 22:58 UTC, olipyskoty requested changes
Nice job, just some small typos. This is fun and I'm excited to add this feature to the app!

2022-03-11 22:58 UTC, olipyskoty commented on src/components/GridView/GridView.test.tsx
> +  it('should not render the previous page button when the user is viewing the last page', () => {
should this be `should not render the next page button ...`

2022-03-14 20:56 UTC, timmydoza commented on src/components/VideoProvider/useLocalTracks/useLocalTracks.ts
> +    console.log(3);
I think I removed this just before you submitted the review 🙂. I'm not sure why it reappeared though!

2022-03-14 22:34 UTC, olipyskoty approved these changes

2022-03-14 23:23 UTC, merged